library IEEE;
use IEEE.std_logic_1164.all;

library XILINXCORELIB;
use XILINXCORELIB.all;

entity RAM is
PORT (
    clka : IN STD_LOGIC;
    wea : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    addra : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    dina : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    douta : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
  );
 end RAM;

architecture coregen of RAM is
-- The following component declsrstion code
-- was pasted directly from the file
-- main_memory.vho which was genereated by coregen

------------- Begin Cut here for COMPONENT Declaration ------ COMP_TAG
COMPONENT main_memory
  PORT (
    clka : IN STD_LOGIC;
    wea : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
    addra : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
    dina : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    douta : OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
  );
END COMPONENT;
-- COMP_TAG_END ------ End COMPONENT Declaration ------------

begin 

-- The following component instantiation code 
-- segment was copied from the main_memory.vho
-- file generated by coregen and the modified 
-- to comply with the rest of the code

------------- Begin Cut here for INSTANTIATION Template ----- INST_TAG
ram0 : main_memory
  PORT MAP (
    clka => clka,
    wea => wea,
    addra => addra,
    dina => dina,
    douta => douta
  );
-- INST_TAG_END ------ End INSTANTIATION Template ------------

end coregen;